Update dependencies and changelog, fix minor deprecation warnings.

diff --git a/vendor/github.com/uber-go/tally/v4/Makefile b/vendor/github.com/uber-go/tally/v4/Makefile
--- a/vendor/github.com/uber-go/tally/v4/Makefile
+++ b/vendor/github.com/uber-go/tally/v4/Makefile
@@ -1,52 +1,82 @@
-export GO15VENDOREXPERIMENT=1
+# "go install"-ed binaries will be placed here during development.
+export GOBIN ?= $(shell pwd)/bin
 
 BENCH_FLAGS ?= -cpuprofile=cpu.pprof -memprofile=mem.pprof -benchmem
-PKGS ?= $(shell glide novendor)
-PKG_FILES ?= *.go example/*.go m3/*.go m3/customtransports m3/thriftudp
+GO_FILES = $(shell find . \
+	   '(' -path '*/.*' -o -path './thirdparty/*' -prune ')' -o \
+	   '(' -type f -a -name '*.go' ')' -print)
+MODULES = . ./tools
+
 LINT_IGNORE = m3/thrift\|thirdparty
-LICENSE_IGNORE = thirdparty
+LICENSE_IGNORE = m3/thrift\|thirdparty
+STATICCHECK_IGNORE = m3/thrift\|thirdparty\|m3/resource_pool.go:.*releaseProto is unused\|m3/reporter.go:.* argument should be pointer-like to avoid allocations
+
+GOLINT = $(GOBIN)/golint
+STATICCHECK = $(GOBIN)/staticcheck
 
 .PHONY: all
 all: lint test
 
-.PHONY: dependencies
-dependencies:
-	@echo "Installing Glide and locked dependencies..."
-	glide --version || go get -u -f github.com/Masterminds/glide
-	glide install
-	@echo "Installing test dependencies..."
-	go install ./vendor/github.com/axw/gocov/gocov
-	go install ./vendor/github.com/mattn/goveralls
-	@echo "Installing golint..."
-	go install ./vendor/github.com/golang/lint/golint
-
 .PHONY: lint
-lint: gomodtidy
-	@rm -rf lint.log
-	@echo "Checking formatting..."
-	@gofmt -d -s $(PKG_FILES) 2>&1 | grep -v '$(LINT_IGNORE)' | tee lint.log
-	@echo "Installing test dependencies for vet..."
-	@go test -i $(PKGS)
+lint: gofmt golint gomodtidy staticcheck license
+
+.PHONY: golint
+golint: $(GOLINT)
 	@echo "Checking lint..."
-	@$(foreach dir,$(PKGS),golint $(dir) 2>&1 | grep -v '$(LINT_IGNORE)' | tee -a lint.log;)
-	@echo "Checking for unresolved FIXMEs..."
-	@git grep -i fixme | grep -v -e vendor -e Makefile | grep -v '$(LINT_IGNORE)' | tee -a lint.log
-	@echo "Checking for license headers..."
-	@./check_license.sh | grep -v '$(LICENSE_IGNORE)' | tee -a lint.log
-	@[ ! -s lint.log ]
+	@$(eval LOG := $(shell mktemp -t log.XXXXX))
+	@$(GOLINT) ./... | grep -v '$(LINT_IGNORE)' > $(LOG) || true
+	@[ ! -s "$(LOG)" ] || \
+		(echo "golint failed:" | \
+		cat - $(LOG) && false)
+
+$(GOLINT): tools/go.mod
+	cd tools && go install golang.org/x/lint/golint
+
+.PHONY: staticcheck
+staticcheck: $(STATICCHECK)
+	@echo "Checking staticcheck..."
+	@$(eval LOG := $(shell mktemp -t log.XXXXX))
+	@$(STATICCHECK) ./... | grep -v '$(STATICCHECK_IGNORE)' > $(LOG) || true
+	@[ ! -s "$(LOG)" ] || \
+		(echo "staticcheck failed:" | \
+		cat - $(LOG) && false)
+
+$(STATICCHECK):
+	cd tools && go install honnef.co/go/tools/cmd/staticcheck
+
+.PHONY: gofmt
+gofmt:
+	@echo "Checking formatting..."
+	$(eval LOG := $(shell mktemp -t log.XXXXX))
+	@gofmt -e -s -l $(GO_FILES) | grep -v '$(LINT_IGNORE)' > $(LOG) || true
+	@[ ! -s "$(LOG)" ] || \
+		(echo "gofmt failed. Please reformat the following files:" | \
+		cat - $(LOG) && false)
+
 
 .PHONY: gomodtidy
 gomodtidy: go.mod go.sum
-	go mod tidy
+	@echo "Checking go.mod and go.sum..."
+	@$(foreach mod,$(MODULES),\
+		(cd $(mod) && go mod tidy) &&) true
 	@if ! git diff --quiet $^; then \
 		echo "go mod tidy changed files:" && \
 		git status --porcelain $^ && \
 		false; \
 	fi
 
+.PHONY: license
+license: check_license.sh
+	@echo "Checking for license headers..."
+	$(eval LOG := $(shell mktemp -t log.XXXXX))
+	@./check_license.sh | grep -v '$(LICENSE_IGNORE)' > $(LOG) || true
+	@[ ! -s "$(LOG)" ] || \
+		(echo "Missing license headers in some files:" | \
+		cat - $(LOG) && false)
+
 .PHONY: test
 test:
-	go test -race -v $(PKGS)
+	go test -race -v ./...
 
 .PHONY: examples
 examples:
@@ -58,13 +88,11 @@ examples:
 
 .PHONY: cover
 cover:
-	go test -cover -coverprofile cover.out -race -v $(PKGS)
-
-.PHONY: coveralls
-coveralls:
-	goveralls -service=travis-ci || echo "Coveralls failed"
+	go test -cover -coverprofile=cover.out -coverpkg=./... -race -v ./...
+	go tool cover -html=cover.out -o cover.html
 
 .PHONY: bench
 BENCH ?= .
 bench:
-	@$(foreach pkg,$(PKGS),go test -bench=$(BENCH) -run="^$$" $(BENCH_FLAGS) $(pkg);)
+	go test -bench=$(BENCH) -run="^$$" $(BENCH_FLAGS) ./...
+
